<?php
/** @var $collection */
$collection = $block->getInfo();
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption">Agent</caption>
        <thead>
        <tr>
            <th scope="col" class="col id">FirstName</th>
            <th scope="col" class="col date">LastName</th>
            <th scope="col" class="col total">Email</th>
            <th scope="col" class="col status">Phone</th>
            <th scope="col" class="col actions">Actions</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($collection as $data): ?>
            <tr>
                <td class="col id"><?php echo $data['first_name'] ?></td>
                <td class="col id"><?php echo $data['last_name'] ?></td>
                <td class="col id"><?php echo $data['email'] ?></td>
                <td class="col id"><?php echo $data['phone'] ?></td>
                <td>
                    <form action="<?= $this->getUrl('agent/info/delete') ?>" method="post">
                        <input type="hidden" name="id"
                               value="<?php echo $data['id']; ?>">
                        <input type="submit" value="Delete" name="submit">
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
